apiVersion: v1
kind: Service
metadata:
  name: pod3-service
spec:
  ports: 
  - port: 31001
    nodePort: 31002
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: k8s-demo
  type: NodePort
